units: units.tsv

ref:
  genomefa: "/data/gpfs/assoc/inbre/hansvg/common_references/Astyanax_mexicanus/Astyanax_mexicanus.Astyanax_mexicanus-2.0.dna.toplevel.fa"
  # gtf file with transcripts
  annotation: "/data/gpfs/assoc/inbre/hansvg/common_references/Astyanax_mexicanus/Astyanax_mexicanus.Astyanax_mexicanus-2.0.103.gtf"
  annotationrseqc: "/data/gpfs/assoc/inbre/hansvg/common_references/Astyanax_mexicanus/Astyanax_mexicanus.Astyanax_mexicanus-2.0.103.gtf"
  adapter: "/data/projects/common_references/raw/CustomBlacklist.fa"

params:
  featurecounts: "-p -C -t exon -g gene_id --extraAttributes gene_symbol,transcript_id,transcript_symbol"
  featurecountsmulti: "-p -M -t exon -g gene_id --extraAttributes gene_symbol,transcript_id,transcript_symbol"
